ALTER TABLE reviews DROP COLUMN title;

ALTER TABLE films CHANGE COLUMN genre summary VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE films MODIFY summary VARCHAR(1000);

ALTER TABLE reviews MODIFY body VARCHAR(1500);